# 💡 MosaicPi_Guide: **"Linear Algebra in MosaicPi"**

> All code and examples are shared to help researchers, students, and engineers understand the reasoning behind DDDA — and to make it easy to apply dimensional analysis to your own data.  
> This notebook serves as an entry-level guide for teaching, validating physical models, and enabling domain-specific knowledge engineering through data-driven dimensional reasoning.

---

## 🎯 What You'll Learn

**MosaicPi中的线性代数应用**

This notebook introduces the **fundamental concepts of linear algebra** that are widely used in applied mathematics, data science, physics, and engineering. The focus is on building an intuitive understanding alongside practical computations using NumPy.

1. **物理模型，隐函数，流形**  
   Understand why we reduce variables and how dimensional consistency enables model generalization.

2. **变量组合**  
   Encode physical units of input quantities using base units and build the D-matrix.

3. **变量组合评估**  
   Discover dimensionless groups by solving linear algebraic equations on the D-matrix.

4. **显式化策略可视化**  
   Learn to assess whether derived groups make physical and computational sense.

5. **不确定性定量化**  
   Set the stage for further steps in the DDDA pipeline including Pi-group selection, uncertainty quantification, and regime detection.

---

## 👤 Author

- **Name**: Jiashun Pang  
- **Created**: August 2025  
- **Affiliation**: MosaicPi, open research notebook  
- **Notebook Focus**:  
  A hands-on exploration of dimensional analysis — from aggregated raw quantities to symbolic Pi-group discovery and preparation for downstream DDDA tasks.

---

📌 *This notebook is designed to be accessible for learners new to dimensional analysis, while also laying the foundation for advanced applications in the full MosaicPi pipeline.*

---

# 1. Linear Algebra Basics Notebook


---

1. **Vectors and Matrices**  
   - Representation of vectors and matrices in NumPy.
   - Basic operations and data structures.

2. **Vector Norms**  
   - $L^1$ norm (Manhattan distance).  
   - $L^2$ norm (Euclidean distance).  
   - $L^\infty$ norm (Maximum absolute value).

3. **Matrix Norms**  
   - Frobenius norm (energy of the matrix).  
   - Spectral norm (largest singular value).

4. **Inner and Outer Products**  
   - Inner product (dot product): geometric interpretation as projection and angle measure.  
   - Outer product: building higher-rank structures from vectors.

5. **Linear Mappings and Basis Change**  
   - How matrices act as linear transformations.  
   - Representing vectors in different bases.

6. **Coordinate Transformations**  
   - Rotation, scaling, and shear using transformation matrices.

7. **Basis Orthogonalization (Gram–Schmidt)**  
   - Process of turning a general basis into an orthogonal (or orthonormal) basis.  
   - Key for numerical stability and eigen-decomposition.

---

Each section contains **Python code examples** with NumPy, allowing you to experiment directly and visualize the underlying operations. This notebook serves as both a **reference guide** and a **hands-on tutorial** for refreshing or learning the essentials of linear algebra.

---

# Linear Algebra Basics Notebook

## 1. Vectors and Matrices

1. **向量 (Vector)**

   * **对象**：表示一个量（点、方向、状态）。
   * **直观理解**：

     * 在物理里，速度向量表示“往哪里、快多少”。
     * 在几何里，向量是空间中的“箭头”。
   * **作用**：通常用来描述“运动/状态/位置”。

2. **矩阵 (Matrix)**

   * **对象**：表示一种线性变换（operator），告诉你如何把一个向量变成另一个向量。
   * **直观理解**：

     * 旋转矩阵：把所有向量都绕原点转一定角度。
     * 缩放矩阵：把所有向量拉长或压缩。
     * 剪切矩阵：把方形变成平行四边形。
   * **作用**：通常用来描述“变化/变换规则”。

---

### 📐 二者的关系

* **向量是“被变换的对象”**

  * 你把向量 $x$ 交给矩阵 $A$，得到一个新的向量 $Ax$。
* **矩阵是“变换的工具”**

  * 它定义了这个空间里所有向量如何一起被改变。

---

### ✅ 一句话总结

* **向量** → 静态的量，表示“点/方向/状态/运动”。
* **矩阵** → 动态的规则，表示“如何把向量整体改变”。

---

In [12]:
import numpy as np

# Vector and matrix examples
v = np.array([1, 2, 3])
M = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])

print("Vector v:", v)
print("Matrix M:\n", M)

Vector v: [1 2 3]
Matrix M:
 [[1 2 3]
 [3 4 5]
 [5 6 7]]


## 2. **Vector Norms**

**范数（Norm）就是一种“长度/大小”的度量方式**，它把一个向量或矩阵映射为一个非负实数，用来回答“这个对象有多大”。

具体作用可以总结为：

1. **度量距离**

   * 通过不同范数，可以定义不同的“距离”概念（直线距离、走方格距离、最大分量差距等）。
   * 应用于几何、机器学习中的相似度计算。

2. **衡量大小/误差**

   * 向量范数衡量数据点的大小，矩阵范数衡量算子的作用强度。
   * 常用于误差分析（\$L^2\$ → 平均误差，\$L^\infty\$ → 最坏情况误差）。

3. **正则化与约束**

   * 优化问题中加入范数作为正则项，控制解的稀疏性、平滑性或稳定性。
   * 例如：\$L^1\$ 正则（稀疏解）、\$L^2\$ 正则（平滑解）。

4. **数值稳定性分析**

   * 在数值计算中，通过范数定义矩阵的 **条件数**，用于判断算法的稳定性与敏感性。

---

👉 一句话总结：
**范数的本质就是给向量或矩阵定义一个“大小”，并在此基础上建立距离、误差和稳定性分析的工具。**

---

### 1. **\$L^1\$ 范数 (Manhattan distance, 曼哈顿距离)**

公式：

$$
\|x\|_1 = \sum_{i=1}^n |x_i|
$$

* **直观意义**：从坐标原点到某点的“走方格”的距离，就像在纽约曼哈顿的街道上走，必须沿着横纵方向走。
* **例子**：
  向量 $x = (3, -4)$
  $\|x\|_1 = |3| + |-4| = 7$
  → 如果你要从 (0,0) 走到 (3,-4)，只能走横纵方向的话，总共要走 7 步。

**应用场景**：稀疏模型（如 Lasso 回归）会用到 \$L^1\$ 范数，因为它倾向于产生稀疏解（很多系数被压缩为零）。

---

### 2. **\$L^2\$ 范数 (Euclidean distance, 欧几里得距离)**

公式：

$$
\|x\|_2 = \sqrt{\sum_{i=1}^n x_i^2}
$$

* **直观意义**：从原点到该点的“直线距离”，就是平时最熟悉的几何距离。
* **例子**：
  向量 $x = (3, -4)$
  $\|x\|_2 = \sqrt{3^2 + (-4)^2} = \sqrt{25} = 5$
  → 就是从 (0,0) 直接走一条直线到 (3,-4) 的最短距离。

**应用场景**：常用于机器学习的损失函数，比如最小二乘法 (least squares)，因为它衡量的是误差的平方和。

---

### 3. **\$L^\infty\$ 范数 (Maximum norm, 最大范数)**

公式：

$$
\|x\|_\infty = \max_i |x_i|
$$

* **直观意义**：从原点到点的距离，用“最大分量”来衡量。换句话说，看你在所有坐标方向上哪一个最远。
* **例子**：
  向量 $x = (3, -4)$
  $\|x\|_\infty = \max(|3|, |-4|) = 4$
  → 意味着走到 (3,-4) 时，最大的坐标偏移量是 4。

**应用场景**：常用于误差上界的分析。比如在数值计算中，\$L^\infty\$ 范数衡量“最坏情况下的误差”。

---

### 🔎 对比总结

* \$L^1\$ → 走格子距离 → 强调“整体偏移量”。
* \$L^2\$ → 直线距离 → 强调“几何上的真实距离”。
* \$L^\infty\$ → 最大坐标差 → 强调“最坏情况”。

---



In [13]:
from numpy.linalg import norm


# L1 norm (Manhattan)
l1_norm = norm(v, 1)
# L2 norm (Euclidean)
l2_norm = norm(v, 2)
# Infinity norm (max-abs)
inf_norm = norm(v, np.inf)


print("L1 norm:", l1_norm)
print("L2 norm:", l2_norm)
print("Infinity norm:", inf_norm)

L1 norm: 6.0
L2 norm: 3.7416573867739413
Infinity norm: 3.0


## 3. **Matrix Norms**

和向量范数一样，**矩阵范数**是衡量矩阵“大小”的工具，但它强调的是矩阵作为线性变换的作用强度或元素整体规模。

---

#### 1. **Frobenius Norm**

$$
\|A\|_F = \sqrt{\sum_{i,j} |a_{ij}|^2}
$$

* **直观意义**：把矩阵所有元素展开成一个大向量，再算 \$L^2\$ 范数。
* **几何解释**：衡量矩阵的“能量”或总信息量。
* **应用**：常用于误差度量，比如比较近似矩阵与原矩阵的差距。

---

#### 2. **Spectral Norm**

$$
\|A\|_2 = \sigma_{\max}(A)
$$

* **直观意义**：矩阵作用在所有向量上的最大“放大倍数”。
* **几何解释**：矩阵把单位球映射成椭球，谱范数就是椭球的最长半径。
* **应用**：常用于稳定性和条件数分析，因为它反映了矩阵最强的线性拉伸能力。

---

#### 3. **Spectral Radius**

$$
\rho(A) = \max \{|\lambda| : \lambda \in \sigma(A)\}
$$

* **直观意义**：所有特征值的模中取最大值，表示矩阵在某个特征方向上的最大伸缩因子。
* **几何解释**：刻画了矩阵在长期作用下的“最强增长模式”。
* **应用**：

  * **迭代法收敛性**：若迭代矩阵的谱半径 \$\rho(A)<1\$，迭代过程收敛。
  * **动力系统稳定性**：在离散系统 \$x\_{k+1}=Ax\_k\$ 中，若 \$\rho(A)<1\$，解会趋向于零。
  * **对比谱范数**：谱半径 ≤ 谱范数；当矩阵是正规矩阵（如对称矩阵）时，二者相等。

---

👉 **概括一句话**：

* Frobenius norm → **整体能量**（看所有元素）。
* Spectral norm → **最强作用**（看最大奇异值）。
* Spectral radius → **长期主导效应**（看最大特征值模）。

---

In [14]:
# Frobenius norm
fro_norm = norm(M, 'fro')
# Spectral norm (largest singular value)
spectral_norm = norm(M, 2)

print("Frobenius norm:", fro_norm)
print("Spectral norm:", spectral_norm)

# 计算谱半径
eigenvalues = np.linalg.eigvals(M)
spectral_radius = max(abs(eigenvalues))

print("Spectral radius:", spectral_radius)


Frobenius norm: 13.19090595827292
Spectral norm: 13.15934799669309
Spectral radius: 12.928203230275507


---

## 4. Inner Product and Outer Product

### 1. **Inner Product（内积 / 点积）**

公式（向量 $x, y \in \mathbb{R}^n$）：

$$
\langle x, y \rangle = x \cdot y = \sum_{i=1}^n x_i y_i
$$

* **几何解释**：

  * 衡量两个向量的 **相似性**。
  * $\langle x, y \rangle = \|x\|\|y\|\cos\theta$，可用来计算夹角。
  * 内积大 → 向量方向接近；内积为 0 → 向量正交。
* **应用**：投影、余弦相似度、能量计算。

---

### 2. **Outer Product（外积）**

公式（向量 $x \in \mathbb{R}^m, y \in \mathbb{R}^n$）：

$$
x \otimes y = x y^T
$$

* **几何解释**：

  * 生成一个 **矩阵/张量**，每个元素是分量的乘积。
  * 用两个向量“拼接”出更高维的结构。
* **应用**：

  * 构造秩一矩阵（低秩近似的基本单元）。
  * 在机器学习中用于表示协方差矩阵、注意力机制（query-key 外积）。

---

👉 **一句话总结**：

* **内积**：衡量向量之间的关系（角度、投影、相似性）。
* **外积**：用向量构造更高阶结构（矩阵、张量、低秩分解）。

好问题 👌！你抓住了“向量的内积/外积”往往是初学重点，但其实在 **矩阵层面**也有对应的“内积/外积”概念。我们分开说：

---

### 3. **矩阵的内积 (Matrix Inner Product)**

对于两个相同大小的矩阵 $A, B \in \mathbb{R}^{m \times n}$，定义 **Frobenius 内积**：

$$
\langle A, B \rangle_F = \text{trace}(A^T B) = \sum_{i=1}^m \sum_{j=1}^n a_{ij} b_{ij}
$$

* **直观意义**：把矩阵看作“大向量”，逐元素相乘后求和。
* **应用**：

  * 用它定义 Frobenius 范数：$\|A\|_F = \sqrt{\langle A, A \rangle_F}$。
  * 在优化/机器学习里用作矩阵之间的“相似度度量”。

👉 这就是向量内积的自然推广。

---

### 2. **矩阵的外积 (Matrix Outer Product)**

严格来说，“外积”通常是 **向量和向量**之间的概念，得到的是矩阵。
但如果你想推广到矩阵层面，可以有两种理解方式：

1. **Kronecker 积 (Kronecker Product)**
   对于矩阵 $A \in \mathbb{R}^{m \times n}$, $B \in \mathbb{R}^{p \times q}$，

   $$
   A \otimes B = 
   \begin{bmatrix}
   a_{11}B & a_{12}B & \cdots & a_{1n}B \\
   a_{21}B & a_{22}B & \cdots & a_{2n}B \\
   \vdots  & \vdots  & \ddots & \vdots \\
   a_{m1}B & a_{m2}B & \cdots & a_{mn}B
   \end{bmatrix}
   $$

   * 这是“矩阵版的外积”，常用于张量构造。
   * 在量子力学、信号处理里很常见。

2. **向量化后做外积**

   * 先把矩阵展平成向量（vec 操作），然后再做普通外积：

     $$
     \text{vec}(A) \, \text{vec}(B)^T
     $$
   * 得到一个更高维的矩阵，常用于机器学习中的特征交叉。

---

## 📐 总结

* **矩阵内积**：$\langle A,B\rangle = \text{trace}(A^T B)$，类似向量点积。
* **矩阵外积**：没有唯一标准，但常用 **Kronecker 积** 或 **向量化后做外积**。

---

👉 一句话：
**矩阵的内积很自然（trace 公式），矩阵的外积则要么用 Kronecker 积，要么通过向量化来定义。**


In [ ]:

# Inner product (dot product)
inner = np.dot(v, v)

# Outer product
outer = np.outer(v, v)

print("Inner product:", inner)
print("Outer product:\n", outer)



---

## 5. Linear Mappings and Basis Change

### 1. **Linear Mappings（线性映射）**

* **矩阵的角色**：矩阵不仅仅是数字表格，它本质上是 **线性变换的算子**。
* **作用方式**：当矩阵 $A$ 作用在向量 $x$ 上时，得到的结果 $Ax$ 表示“把向量 $x$”在空间中 **拉伸、缩放、旋转或反射**。
* **几何意义**：矩阵可以把单位正方形/单位圆变换成平行四边形/椭圆。

---

### 2. **Basis Change（基变换）**

* **基的意义**：基（basis）是描述空间中向量的一组“坐标尺”。
* **基变换过程**：同一个向量，可以在不同基下有不同的坐标表示。

  $$
  [x]_{new} = P^{-1} [x]_{old}
  $$

  其中 $P$ 是基变换矩阵。
* **应用**：

  * 坐标系切换（如从直角坐标系到极坐标系）。
  * 对角化、主成分分析（PCA），通过换基揭示数据的本质方向。

---

👉 **一句话总结**：

* **矩阵**：是线性变换的工具，控制向量在空间中的形状变化。
* **基变换**：是重新选择坐标系，用新的“尺子”来描述同一个向量或变换。


In [ ]:
# Linear mapping: matrix acting on vector
A = np.array([[2, 0], [0, 3]])
x = np.array([1, 1])
y = A @ x
print("Linear mapping result y:", y)

# Basis change example
P = np.array([[1, 1], [0, 1]])   # Change of basis matrix
x_new_basis = np.linalg.inv(P) @ x
print("Coordinates of x in new basis:", x_new_basis)



---

## 6. Coordinate Transformation

**坐标变换**是通过矩阵来对向量或图形进行操作，本质是对坐标系的重新刻画。

### 常见的三类变换

1. **Rotation（旋转）**

   * 用正交矩阵（旋转矩阵）实现：

     $$
     R(\theta) = \begin{bmatrix} 
     \cos\theta & -\sin\theta \\ 
     \sin\theta & \cos\theta 
     \end{bmatrix}
     $$
   * 保持向量长度和角度不变，只改变方向。

2. **Scaling（缩放）**

   * 用对角矩阵实现：

     $$
     S = \begin{bmatrix} 
     s_x & 0 \\ 
     0 & s_y 
     \end{bmatrix}
     $$
   * 在不同方向上拉伸或压缩。

3. **Shear（剪切/错切）**

   * 用非对角元实现：

     $$
     H = \begin{bmatrix} 
     1 & k \\ 
     0 & 1 
     \end{bmatrix}
     $$
   * 把正方形变成平行四边形，角度发生改变但面积可能保持。

---

👉 **一句话总结**：
坐标变换就是用矩阵来控制图形的 **方向（旋转）、大小（缩放）、形状（剪切）**。

---


In [ ]:

# Rotate a vector by 90 degrees counter-clockwise
rotation_matrix = np.array([[0, -1], [1, 0]])
vector = np.array([1, 0])
rotated_vector = rotation_matrix @ vector

print("Original vector:", vector)
print("Rotated vector:", rotated_vector)

---

## 7. Basis Orthogonalization (Gram–Schmidt)

### 1. **问题背景**

* 在许多场景中（如数值计算、信号处理、PCA），我们希望一组基底向量 **互相正交**，这样计算更简洁稳定。
* 一般给定的一组向量并不正交，需要用 **Gram–Schmidt 正交化** 来处理。

---

### 2. **Gram–Schmidt 过程**

输入：一组线性无关向量 $\{v_1, v_2, ..., v_n\}$。
输出：一组正交（或正交归一）基 $\{u_1, u_2, ..., u_n\}$。

步骤：

1. 取第一个向量：

   $$
   u_1 = v_1
   $$
2. 对后续每个向量，逐步减去它在已有正交基上的投影：

   $$
   u_k = v_k - \sum_{j=1}^{k-1} \frac{\langle v_k, u_j \rangle}{\langle u_j, u_j \rangle} u_j
   $$
3. 若需要正交**归一**基，再把每个 $u_k$ 归一化：

   $$
   e_k = \frac{u_k}{\|u_k\|}
   $$

### 3. **线性无关**
一组 **正交向量**

$$
u_1 = (1,0), \quad u_2 = (0,1)
$$

* 内积：

  $$
  \langle u_1, u_2 \rangle = 1 \cdot 0 + 0 \cdot 1 = 0
  $$
* ✅ 它们正交（互相垂直），而且显然线性无关。

---

一组 **线性无关但不正交的向量**

$$
v_1 = (1,0), \quad v_2 = (1,1)
$$

* 内积：

  $$
  \langle v_1, v_2 \rangle = 1 \cdot 1 + 0 \cdot 1 = 1 \neq 0
  $$
* ❌ 它们不正交（不垂直）。
* 但它们 **线性无关**，因为：

  $$
  v_2 \neq \alpha v_1 \quad \text{对任意实数 }\alpha
  $$

  （即 $v_2$ 不是 $v_1$ 的倍数）。

👉 这说明：这两个向量虽然“歪歪斜斜”，但依然能张成整个二维平面。

---
直观解释

* “线性无关” = 它们指向不同的方向，能覆盖更大的空间。
* “正交” = 不仅方向不同，而且完全没有重叠分量。
* 所以：

  * 所有正交向量组一定线性无关。
  * 但并不是所有线性无关向量组都正交。

---

✅ 一句话总结：
$(1,0)$ 和 $(1,1)$ 是 **线性无关但不正交** 的典型例子。

---

### 3. **直观解释**

* 就像把一组“歪斜”的向量，逐个“投影并减掉重叠部分”，最后得到一组互相垂直的“新尺子”。
* **几何意义**：在原空间不变的前提下，重新选一组彼此正交的基。

---

### 4. **应用**

* QR 分解的基础（矩阵分解、数值稳定计算）。
* 简化几何或代数运算（正交基下点积、投影更方便）。
* 数据降维（PCA 中的正交化步骤）。

---

👉 **一句话总结**：
Gram–Schmidt 正交化就是一种系统方法，把任意一组线性无关向量“修正”为互相正交（或标准正交）的基底。


In [15]:

def gram_schmidt(vectors):
    orthogonal = []
    for v in vectors:
        w = v - sum(np.dot(v, u)/np.dot(u, u) * u for u in orthogonal)
        if np.linalg.norm(w) > 1e-10:
            orthogonal.append(w)
    return np.array(orthogonal)

# Example basis
B = np.array([[1, 1], [1, 0]], dtype=float)
orthogonal_basis = gram_schmidt(B)

print("Original basis:\n", B)
print("Orthogonalized basis:\n", orthogonal_basis)

Original basis:
 [[1. 1.]
 [1. 0.]]
Orthogonalized basis:
 [[ 1.   1. ]
 [ 0.5 -0.5]]
